services:
  app:
    build:
      context: footballapi/
    ports:
      - "8000:8000"
    volumes:
      - ./footballapi/src:/src
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
    #command: ["python3", "src/db.py"]
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=pass
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - db
      - rabbitmq
    networks:
      - backend
    container_name: app

  db:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
    networks:
      - backend
    container_name: db
    volumes:
    - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "5432:5432"
    
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - backend
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

networks:
  backend:
